### PR TITLE
Fix/chain and token load

### LINKED ISSUE #47: [ADD] Airdrop not live banner
So users know that airdrop is not live yet, please add a banner.

image
https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=18470-24982&t=IP1epZTUiawi52BQ-4

### LINKED ISSUE #54: [BUG] No price fetching for CACAO
**Describe the bug**
CACAO price is not fetching and displaying `0`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Ehsan-saradar**
- Fix #54
- Fix #47 
- Update leader board
- Optimize add new chain
- Updated saver/lp

### CODE REVIEW

File: src/modals/join-airdrop/index.tsx [hunk 1]
```diff
@@ -86,88 +66,96 @@ const Component: FC = () => {
...
+                  >
+                    Inspect the code here.
+                  </a>
+                </div>
+
+                <div className="text">
+                  <span className="desc">
+                    Your Airdrop Share is based on how long you have kept funds
+                    in Vultisig for. Only Layer1 assets and tokens on the 1inch
+                    Token List apply.
```
Comment (realpaaao) [inline src/modals/join-airdrop/index.tsx:131]: Please change the paragraph to:
`Your Airdrop Share is based on the amount of assets in Vultisig multiplied by time in Vaults.  The assets counted for the airdrop can be seen here.`

Link the `here` to: [docs](https://docs.vultisig.com/vultisig-token/airdrop#eligble-assets)

Comment (johnnyluo) [reply src/modals/join-airdrop/index.tsx:131]: I will get this one merged and deployed it first , please address this in a seperate PR?

**Review by johnnyluo — APPROVED** [review]
LGTM
